name: x86-Darwin

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Spec
        run: |
          sysctl -n machdep.cpu.brand_string
          top -l 1 -s 0 | grep PhysMem
      - name: Install Dependencies
        run: |
          brew install llvm@9
          pip install lit
      - name: Build HelloWorld
        run: |
          cd HelloWorld
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/local/opt/llvm@9/"  ../
          make -j2
      - name: Build llvm-tutor + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLT_LLVM_INSTALL_DIR="/usr/local/opt/llvm@9/"  ../
          make -j2
          lit test/
